# Generated by Django 5.2.5 on 2025-09-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0010_remove_gamification_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='logrousuario',
                    name='logro',
                ),
                migrations.AlterUniqueTogether(
                    name='logrousuario',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='logrousuario',
                    name='usuario',
                ),
                migrations.RemoveField(
                    model_name='racha',
                    name='usuario',
                ),
                migrations.DeleteModel(
                    name='Logro',
                ),
                migrations.DeleteModel(
                    name='LogroUsuario',
                ),
                migrations.DeleteModel(
                    name='Racha',
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='EstadisticaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-año', '-mes'],
                'unique_together': {('usuario', 'año', 'mes')},
            },
        ),
    ]
