# Generated by Django 5.2.5 on 2025-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0011_remove_logrousuario_logro_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='perfilusuario',
                    name='saldo_base',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo base personalizado establecido por el usuario', max_digits=10, null=True),
                ),
            ],
            database_operations=[],
        ),
    ]
