# Generated by Django 5.2.5 on 2025-10-14 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0012_add_saldo_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='GastoPlanificado',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('descripcion', models.CharField(max_length=200)),
                        ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                        ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                        ('año', models.IntegerField()),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                        ('completado', models.BooleanField(default=False)),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Gasto Planificado',
                        'verbose_name_plural': 'Gastos Planificados',
                        'ordering': ['año', 'mes', 'descripcion'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
