# Generated by Django 5.2.5 on 2025-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0013_gastoplanificado'),
    ]

    operations = [
        # Neutralized to prevent inconsistent migration history
    ]
