# Generated by Django 5.2.5 on 2025-10-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0014_fix_migrations'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "gastitos_gastoplanificado" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "descripcion" varchar(200) NOT NULL,
                "monto" decimal NOT NULL,
                "mes" integer NOT NULL,
                "año" integer NOT NULL,
                "fecha_creacion" datetime NOT NULL,
                "completado" bool NOT NULL,
                "usuario_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS gastitos_gastoplanificado;"
        ),
    ]
